### ISSUE TITLE
Facing issue while executing changeset

### ISSUE THREAD

**Issue by rajsekarm1** [coldze/mongol#7]
C:\Users\rajasekarm\go\src\github.com\coldze\mongol>mongol migrate --path=C:\Users\rajasekarm\go\src\github.com\coldze\mongol\test\changelog.json
2019/04/03 19:38:57 [INFO] Migration path: 'C:\Users\rajasekarm\go\src\github.com\coldze\mongol\test\changelog.json'
2019/04/03 19:40:01 [FATAL] App run failed with error: Run failed. Error: C:/Users/rajasekarm/go/src/github.com/coldze/mongol/commands/migrate.go:67
        Error: Changelog validation failed.

C:/Users/rajasekarm/go/src/github.com/coldze/mongol/engine/changelog.go:460
        Error: Failed to apply changes.

C:/Users/rajasekarm/go/src/github.com/coldze/mongol/engine/changelog.go:469
        Error: Failed to process changeset '20180318_00001_00001'

C:/Users/rajasekarm/go/src/github.com/coldze/mongol/primitives/mongo/validator.go:63
        Error: Failed to check change-set with ID 20180318_00001_00001

C:/Users/rajasekarm/go/src/github.com/coldze/mongol/primitives/mongo/validator.go:86
        Error: Failed to get change from DB. Error: server selection error: server selection timeout
current topology: Type: ReplicaSetNoPrimary
Servers:
Addr: app1:27017, Type: Unknown, State: Connected, Avergage RTT: 0, Last error: dial tcp: lookup app1: no such host

Following is the changelog json file.

{
  "connection": "mongodb://aos:ChgMeNOW@localhost:3339/nc",
  "dbname": "nc",
  "migrations": [
    {
      "include": "20180318_00001/changelog.json",
      "relativeToChangelogFile": true
    },
    {
      "include": "20180523_00001/changelog.json",
      "relativeToChangelogFile": true
    }
  ]
}

**Comment by coldze** [comment]
Hi @rajsekarm1,

Please check once more content of your `changelog.json` file, as it turns out from log you provided, mongodb driver is trying to connect to `app1:27017` and connection string in `changelog.json` states completely different host/port.
It seems that it is either an error in `changelog.json` file in connection string or there is something wrong with mongo configuration on your machine, because the lowest error:
```
server selection error: server selection timeout
current topology: Type: ReplicaSetNoPrimary
Servers:
Addr: app1:27017, Type: Unknown, State: Connected, Avergage RTT: 0, Last error: dial tcp: lookup app1: no such host
```
It comes from mongodb driver.

Are you able to connect using `connection` from `changelog.json` as connection-uri parameter for `mongo` utils?
